logging:
  level: INFO
  loggers:
    org.softwire.training: DEBUG

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: mysql

  # verifyServerCertificate=false to avoid log spam
  url: jdbc:mysql://localhost/socialnetwork?verifyServerCertificate=false&useSSL=true

  properties:
    charSet: UTF-8

  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute